version: '3.0'

services:
  app:
    build:
      context: .
    environment:
      DATA_PATH: /docker_vol/
    volumes:
      - ./docker_vol:/docker_vol/
    command: "uvicorn server:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
